language: python
python:
  - "3.4"
  - "3.5"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - "pip install setuptools --upgrade; python setup.py install"
# command to run tests
script: nosetests
