language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.8"
# command to install dependencies
install:
# - "pip install -r requirements.txt"
  - "pip install setuptools --upgrade; python setup.py install"
# command to run tests
script: nosetests
